# Generated by Django 2.2.6 on 2019-10-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("election", "0003_auto_20171202_1819")]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        )
    ]
