# Generated by Django 4.2.20 on 2025-03-14 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("election", "0004_auto_20191006_0049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidature",
            name="program",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="candidature",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
