# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

multi-ecosystem-groups:
  common:
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "taiste"
    commit-message:
      prefix: "[UPDATE] "

updates:
  - package-ecosystem: "uv"
    patterns: ["*"]
    multi-ecosystem-group: "common"

  - package-ecosystem: "npm"
    patterns: ["*"]
    multi-ecosystem-group: "common"
    groups:
      # npm supports production and development groups, but not uv
      # cf. https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#dependency-type-groups
      main-deps:
        dependency-type: "production"
      dev-deps:
        dependency-type: "development"
