repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.13
    hooks:
      - id: ruff-check  # just check the code, and print the errors
      - id: ruff-check  # actually fix the fixable errors, but print nothing
        args: ["--fix", "--silent"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: v0.6.1
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.4"]
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.7
    hooks:
      - id: djhtml
        name: format templates
        entry: djhtml --tabwidth 2
        types: ["jinja"]
      - id: djcss
        name: format scss files
        entry: djcss --tabwidth 2
        types: ["scss"]
