repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.10
    hooks:
      - id: ruff  # just check the code, and print the errors
      - id: ruff  # actually fix the fixable errors, but print nothing
        args: ["--fix", "--silent"]
      # Run the formatter.
      - id: ruff-format