repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.9
    hooks:
      - id: ruff  # just check the code, and print the errors
      - id: ruff  # actually fix the fixable errors, but print nothing
        args: ["--fix", "--silent"]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.1.0"  # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.3"]
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        name: format templates
        entry: djhtml --tabwidth 2
        types: ["jinja"]
      - id: djcss
        name: format scss files
        entry: djcss --tabwidth 2
        types: ["scss"]
