# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-04 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0029_auto_20180426_2013")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("POSTER_MODERATION", "A new poster needs to be moderated"),
                    ("MAILING_MODERATION", "A new mailing list needs to be moderated"),
                    (
                        "PEDAGOGY_MODERATION",
                        "A new pedagogy comment has been signaled for moderation",
                    ),
                    ("NEWS_MODERATION", "There are %s fresh news to be moderated"),
                    ("FILE_MODERATION", "New files to be moderated"),
                    (
                        "SAS_MODERATION",
                        "There are %s pictures to be moderated in the SAS",
                    ),
                    ("NEW_PICTURES", "You've been identified on some pictures"),
                    ("REFILLING", "You just refilled of %s €"),
                    ("SELLING", "You just bought %s"),
                    ("GENERIC", "You have a notification"),
                ],
                default="GENERIC",
                max_length=32,
                verbose_name="type",
            ),
        )
    ]
