# Generated by Django 2.2.6 on 2019-10-05 22:49

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0032_auto_20190909_0043")]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "permissions": (
                    (
                        "change_prop_page",
                        "Can change the page's properties (groups, ...)",
                    ),
                )
            },
        ),
        migrations.AlterModelManagers(
            name="group",
            managers=[("objects", django.contrib.auth.models.GroupManager())],
        ),
    ]
