# Generated by Django 2.2.10 on 2020-02-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_operationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("MAN", "Man"), ("WOMAN", "Woman")],
                max_length=10,
                null=True,
                verbose_name="sex",
            ),
        ),
    ]
