# Generated by Django 3.2.18 on 2023-05-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_auto_20211105_1708"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferences",
            name="receive_weekmail",
            field=models.BooleanField(
                default=False, verbose_name="receive the Weekmail"
            ),
        ),
    ]
