# Generated by Django 4.2.16 on 2024-11-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_alter_user_options_user_user_permissions_and_more"),
        ("club", "0013_alter_club_board_group_alter_club_members_group_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetaGroup",
        ),
        migrations.DeleteModel(
            name="RealGroup",
        ),
        migrations.AlterModelOptions(
            name="group",
            options={},
        ),
        migrations.RenameField(
            model_name="group",
            old_name="is_meta",
            new_name="is_manually_manageable",
        ),
        migrations.AlterField(
            model_name="group",
            name="is_manually_manageable",
            field=models.BooleanField(
                default=False,
                help_text="If False, this shouldn't be shown on group management pages",
                verbose_name="Is manually manageable",
            ),
        ),
    ]
