# Generated by Django 4.2.17 on 2025-02-25 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_bangroup_alter_group_description_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userban",
            options={"verbose_name": "user ban", "verbose_name_plural": "user bans"},
        ),
    ]
