# Generated by Django 4.2.17 on 2025-01-26 15:01

from typing import TYPE_CHECKING

from django.db import migrations
from django.db.migrations.state import StateApps

if TYPE_CHECKING:
    import core.models


def remove_sas_sithfiles(apps: StateApps, schema_editor):
    SithFile: type[core.models.SithFile] = apps.get_model("core", "SithFile")
    SithFile.objects.filter(is_in_sas=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_bangroup_alter_group_description_alter_user_groups_and_more"),
        ("sas", "0006_alter_peoplepicturerelation_picture_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_sas_sithfiles, reverse_code=migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterModelOptions(
            name="userban",
            options={"verbose_name": "user ban", "verbose_name_plural": "user bans"},
        ),
    ]
