# Generated by Django 4.2.17 on 2025-02-28 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0044_alter_userban_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickUploadImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="upload")),
                ("content_type", models.CharField(max_length=50)),
                (
                    "related_model_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "related_model_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["related_model_type", "related_model_id"],
                        name="core_quicku_related_23899b_idx",
                    )
                ],
            },
        ),
    ]
