# Generated by Django 5.2 on 2025-05-20 17:50
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0045_quickuploadimage")]

    operations = [
        migrations.CreateModel(
            name="GlobalPermissionRights",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [("access_lookup", "Can access any lookup in the sith")],
                "managed": False,
                "default_permissions": [],
            },
        ),
    ]
