# Generated by Django 5.2.1 on 2025-06-11 16:10

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [("core", "0046_permissionrights")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=core.models.get_notification_types,
                default="GENERIC",
                max_length=32,
                verbose_name="type",
            ),
        ),
    ]
