# Generated by Django 5.2.8 on 2025-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0047_alter_notification_date_alter_notification_type")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("view_hidden_user", "Can view hidden users")],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.RenameField(
            model_name="user", old_name="is_subscriber_viewable", new_name="is_viewable"
        ),
        migrations.AlterField(
            model_name="user",
            name="is_viewable",
            field=models.BooleanField(
                default=True,
                verbose_name="Profile visible by subscribers",
                help_text=(
                    "If you disable this option, only admin users "
                    "will be able to see your profile."
                ),
            ),
        ),
    ]
