# Generated by Django 4.2.17 on 2025-02-14 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("core", "0048_remove_sithfiles")]

    operations = [migrations.RemoveField(model_name="sithfile", name="is_in_sas")]
