# Generated by Django 5.2.12 on 2026-03-14 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0048_alter_user_options")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whitelisted_users",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Even if this profile is hidden, "
                    "the users in this list will still be able to see it."
                ),
                related_name="visible_by_whitelist",
                to=settings.AUTH_USER_MODEL,
                verbose_name="whitelisted users",
            ),
        ),
        migrations.AlterField(
            model_name="preferences",
            name="show_my_stats",
            field=models.BooleanField(
                default=False,
                help_text="Allow subscribers to access your AE account stats.",
                verbose_name="show your stats to others",
            ),
        ),
    ]
