# Generated by Django 5.2.17 on 2026-09-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0050_alter_sithfile_moderator")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cgu_approved",
            field=models.BooleanField(default=False, verbose_name="ToS approved"),
        ),
    ]
