# Generated by Django 5.2.17 on 2026-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0050_alter_sithfile_moderator")]

    operations = [
        migrations.AddField(
            model_name="preferences",
            name="show_my_timetable",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Allow subscribers to see your timetable and "
                    "to compare it to theirs (if you have filled it)"
                ),
                verbose_name="show your timetable to others",
            ),
        ),
    ]
