# Generated by Django 3.2.15 on 2022-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eboutic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="quantity"),
        ),
    ]
