# Generated by Django 5.2.11 on 2026-02-22 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("counter", "0039_price"), ("eboutic", "0002_auto_20221005_2243")]

    operations = [
        migrations.RenameField(
            model_name="basketitem", old_name="product_name", new_name="label"
        ),
        migrations.RenameField(
            model_name="basketitem",
            old_name="product_unit_price",
            new_name="unit_price",
        ),
        migrations.RenameField(
            model_name="basketitem", old_name="product_id", new_name="product"
        ),
        migrations.RenameField(
            model_name="invoiceitem", old_name="product_name", new_name="label"
        ),
        migrations.RenameField(
            model_name="invoiceitem",
            old_name="product_unit_price",
            new_name="unit_price",
        ),
        migrations.RenameField(
            model_name="invoiceitem", old_name="product_id", new_name="product"
        ),
        migrations.RemoveField(model_name="basketitem", name="type_id"),
        migrations.RemoveField(model_name="invoiceitem", name="type_id"),
        migrations.AlterField(
            model_name="basketitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="counter.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="counter.product",
                verbose_name="product",
            ),
        ),
    ]
