# Generated by Django 5.2.3 on 2025-10-06 11:24

from django.db import migrations, models

import subscription.models


class Migration(migrations.Migration):
    dependencies = [("subscription", "0015_alter_subscription_location_and_more")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=subscription.models.get_subscription_types,
                max_length=255,
                verbose_name="subscription type",
            ),
        )
    ]
