# Generated by Django 5.2.17 on 2026-09-01 08:44

import django.utils.timezone
from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.models import F, Value
from django.db.models.functions import Least
from django.utils.timezone import now


def make_default_creation_date(apps: StateApps, schema_editor):
    Subscription = apps.get_model("subscription", "Subscription")
    Subscription.objects.update(
        created_at=Least(
            F("subscription_start"), Value(now()), output_field=models.DateTimeField()
        )
    )


class Migration(migrations.Migration):
    dependencies = [("subscription", "0016_alter_subscription_subscription_type")]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text=(
                    "When this subscription was created. "
                    "This date may differ from the start of the subscription."
                ),
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            make_default_creation_date,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
