# Generated by Django 4.2 on 2024-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pedagogy", "0002_auto_20190827_2251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uv",
            name="language",
            field=models.CharField(
                choices=[
                    ("FR", "French"),
                    ("EN", "English"),
                    ("DE", "German"),
                    ("SP", "Spanish"),
                ],
                default="FR",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
