# Generated by Django 5.2.3 on 2025-10-26 10:15

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [("api", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="apiclient",
            name="hmac_key",
            field=models.CharField(
                default=api.models.get_hmac_key, max_length=128, verbose_name="HMAC Key"
            ),
        ),
    ]
