# Generated by Django 5.2 on 2025-04-15 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("launderette", "0001_initial")]

    operations = [
        migrations.DeleteModel(name="Launderette"),
        migrations.DeleteModel(name="Machine"),
        migrations.DeleteModel(name="Slot"),
        migrations.DeleteModel(name="Token"),
    ]
