name: "Setup xapian"
description: "Setup the xapian indexes"
runs:
  using: composite
  steps:
    - name: Setup xapian index
      run: |
        mkdir -p /dev/shm/search_indexes
        ln -s /dev/shm/search_indexes sith/search_indexes
      shell: bash
