# Generated by Django 3.2.16 on 2023-04-12 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("galaxy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="galaxy",
            options={"ordering": ["pk"]},
        ),
        migrations.AddField(
            model_name="galaxystar",
            name="galaxy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stars",
                to="galaxy.galaxy",
                verbose_name="the galaxy this star belongs to",
            ),
        ),
        migrations.AlterField(
            model_name="galaxy",
            name="state",
            field=models.JSONField(null=True, verbose_name="The galaxy current state"),
        ),
        migrations.AlterField(
            model_name="galaxystar",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stars",
                to=settings.AUTH_USER_MODEL,
                verbose_name="star owner",
            ),
        ),
    ]
