# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-18 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("com", "0005_auto_20180318_2227")]

    operations = [migrations.RemoveField(model_name="sith", name="index_page")]
