# Generated by Django 2.2.28 on 2022-07-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0006_remove_sith_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekmail',
            name='type',
            field=models.CharField(choices=[('WEEKMAIL', 'Weekmail'), ('INVITATION', 'Invitation')], default='WEEKMAIL', max_length=16, verbose_name='type'),
        ),
    ]
