# Generated by Django 4.2.17 on 2024-12-16 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0011_auto_20180426_2013"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("com", "0006_remove_sith_index_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="club",
            field=models.ForeignKey(
                help_text="The club which organizes the event.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="club.club",
                verbose_name="club",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A more detailed and exhaustive description of the event.",
                verbose_name="content",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="moderator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_news",
                to=settings.AUTH_USER_MODEL,
                verbose_name="moderator",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="summary",
            field=models.TextField(
                help_text="A description of the event (what is the activity ? is there an associated clic ? is there a inscription form ?)",
                verbose_name="summary",
            ),
        ),
    ]
