# Generated by Django 4.2.17 on 2025-02-28 20:34

import django.db.models.deletion
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_userban_options"),
        ("club", "0013_alter_club_board_group_alter_club_members_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="club", options={"ordering": ["name"]}),
        migrations.RenameField(
            model_name="club",
            old_name="unix_name",
            new_name="slug_name",
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(unique=True, max_length=64, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="club",
            name="slug_name",
            field=models.SlugField(
                editable=False, max_length=30, unique=True, verbose_name="slug name"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=core.fields.ResizedImageField(
                blank=True,
                force_format="WEBP",
                height=200,
                null=True,
                upload_to="club_logos",
                verbose_name="logo",
                width=200,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="page",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club",
                to="core.page",
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A summary of what your club does. This will be displayed on the club list page.",
                max_length=1000,
                verbose_name="short description",
            ),
        ),
    ]
