# Generated by Django 5.2.3 on 2025-09-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("club", "0015_clubrole_alter_membership_role")]

    operations = [
        # because Postgres migrations run in a single transaction,
        # we cannot change the actual values of Membership.role
        # and apply the FOREIGN KEY constraint in the same migration.
        # The data migration was made in the previous migration.
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="club.clubrole",
                verbose_name="role",
            ),
        ),
    ]
