# Generated by Django 5.2.17 on 2026-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0017_linktype_clublink"),
        ("core", "0050_alter_sithfile_moderator"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubrole",
            name="linked_groups",
            field=models.ManyToManyField(
                help_text=(
                    "Groups that are automatically given or removed "
                    "to user receiving or losing this club role"
                ),
                related_name="club_roles",
                to="core.group",
                verbose_name="Linked groups",
            ),
        ),
    ]
