# Generated by Django 5.2.1 on 2025-06-05 10:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("club", "0014_alter_club_options_rename_unix_name_club_slug_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="room name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="description"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BELFORT", "Belfort"),
                            ("SEVENANS", "Sévenans"),
                            ("MONTBELIARD", "Montbéliard"),
                        ],
                        verbose_name="site",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        help_text="The club which manages this room",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservable_rooms",
                        to="club.club",
                        verbose_name="room owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservable room",
                "verbose_name_plural": "reservable rooms",
            },
        ),
        migrations.CreateModel(
            name="ReservationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="comment"),
                ),
                (
                    "start_at",
                    models.DateTimeField(db_index=True, verbose_name="slot start"),
                ),
                ("end_at", models.DateTimeField(verbose_name="slot end")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="reservation.room",
                        verbose_name="reserved room",
                    ),
                ),
            ],
            options={
                "verbose_name": "reservation slot",
                "verbose_name_plural": "reservation slots",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="reservation_slot_end_after_start",
                    )
                ],
            },
        ),
    ]
