# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("counter", "0016_producttype_comment")]

    operations = [
        migrations.CreateModel(
            name="StudentCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(max_length=14, unique=True, verbose_name="uid"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_cards",
                        to="counter.Customer",
                        verbose_name="student cards",
                    ),
                ),
            ],
        )
    ]
