# Generated by Django 3.2.15 on 2022-11-12 12:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0017_studentcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address_1',
            field=models.CharField(max_length=50, null=True, verbose_name='address line 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address_2',
            field=models.CharField(max_length=50, null=True, verbose_name='address line 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_zip_code',
            field=models.CharField(max_length=16, null=True, verbose_name='zip code'),
        ),
    ]
