# Generated by Django 3.2.15 on 2022-11-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counter", "0017_studentcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttype",
            name="priority",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
