# Generated by Django 4.2 on 2024-06-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("counter", "0020_auto_20221215_1709")]

    operations = [
        migrations.RenameField(
            model_name="cashregistersummaryitem",
            old_name="check",
            new_name="is_check",
        ),
        migrations.AlterField(
            model_name="cashregistersummaryitem",
            name="is_check",
            field=models.BooleanField(
                default=False,
                help_text="True if this is a bank check, else False",
                verbose_name="check",
            ),
        ),
    ]
