# Generated by Django 4.2.17 on 2024-12-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counter", "0026_alter_studentcard_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refilling",
            name="payment_method",
            field=models.CharField(
                choices=[("CHECK", "Check"), ("CASH", "Cash"), ("CARD", "Credit card")],
                default="CARD",
                max_length=255,
                verbose_name="payment method",
            ),
        ),
    ]
