# Generated by Django 4.2.17 on 2024-12-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("counter", "0028_alter_producttype_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selling",
            name="label",
            field=models.CharField(max_length=128, verbose_name="label"),
        ),
    ]
