# Generated by Django 4.2.20 on 2025-04-06 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("counter", "0030_returnableproduct_returnableproductbalance_and_more")
    ]

    operations = [
        migrations.AlterModelOptions(
            name="counter",
            options={
                "permissions": [("view_counter_stats", "Can view counter stats")],
                "verbose_name": "counter",
            },
        ),
    ]
