# Generated by Django 5.2 on 2025-06-02 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0014_alter_club_options_rename_unix_name_club_slug_name_and_more"),
        ("counter", "0031_alter_counter_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceCall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validated", models.BooleanField(verbose_name="is validated")),
                (
                    "month",
                    models.PositiveSmallIntegerField(verbose_name="invoice month"),
                ),
                ("year", models.PositiveIntegerField(verbose_name="invoice year")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="club.club"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice call",
                "verbose_name_plural": "Invoice calls",
            },
        ),
    ]
