# Generated by Django 5.2.3 on 2025-11-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("counter", "0033_invoicecall")]

    operations = [
        migrations.AlterField(
            model_name="selling",
            name="date",
            field=models.DateTimeField(db_index=True, verbose_name="date"),
        ),
    ]
