# Generated by Django 5.2.8 on 2025-11-19 17:59

from django.db import migrations, models
from django.db.migrations.state import StateApps


class Migration(migrations.Migration):
    dependencies = [("counter", "0034_alter_selling_date_selling_date_month_idx")]

    operations = [
        migrations.RemoveField(model_name="selling", name="is_validated"),
    ]
