# Generated by Django 5.2.8 on 2025-11-26 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("counter", "0035_remove_selling_is_validated_and_more")]

    operations = [
        migrations.CreateModel(
            name="ProductFormula",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        help_text="The products that constitute this formula.",
                        related_name="formulas",
                        to="counter.product",
                        verbose_name="products",
                    ),
                ),
                (
                    "result",
                    models.OneToOneField(
                        help_text="The formula product.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counter.product",
                        verbose_name="result product",
                    ),
                ),
            ],
        ),
    ]
