# Generated by Django 5.2.13 on 2026-05-13 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("counter", "0039_price")]

    operations = [
        migrations.RemoveField(model_name="product", name="buying_groups"),
    ]
