# Generated by Django 5.2.13 on 2026-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("counter", "0039_price")]

    operations = [
        migrations.RemoveField(model_name="product", name="buying_groups"),
        migrations.AddField(
            model_name="product",
            name="clic_limit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    "If a limit is set, the product won't be purchasable "
                    "anymore once the latter is reached."
                ),
                null=True,
                verbose_name="clic limit",
            ),
        ),
        migrations.RemoveField(model_name="counter", name="token"),
    ]
