# Generated by Django 5.2.14 on 2026-06-02 10:45

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("counter", "0040_product_clic_limit")]

    operations = [
        migrations.AlterField(
            model_name="billinginfo",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="billinginfo",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Phone number"
            ),
        ),
    ]
