# Generated by Django 5.2.15 on 2026-06-07 12:08

from django.db import migrations

import counter.fields


class Migration(migrations.Migration):
    dependencies = [("counter", "0041_alter_billinginfo_country_and_more")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="amount",
            field=counter.fields.CurrencyField(
                decimal_places=2,
                default=0,
                max_digits=12,
                max_value=250,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="refilling",
            name="amount",
            field=counter.fields.CurrencyField(
                decimal_places=2, max_digits=12, min_value=0.01, verbose_name="amount"
            ),
        ),
    ]
