# Generated by Django 4.2.14 on 2024-08-29 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_alter_preferences_receive_weekmail"),
        ("sas", "0002_auto_20161119_1241"),
    ]

    operations = [
        migrations.CreateModel(
            name="SasFile",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.sithfile",),
        ),
    ]
