# Generated by Django 5.2.3 on 2025-06-17 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("sas", "0004_picturemoderationrequest_and_more")]

    operations = [
        migrations.AlterModelOptions(
            name="sasfile",
            options={
                "permissions": [
                    ("moderate_sasfile", "Can moderate SAS files"),
                    ("view_unmoderated_sasfile", "Can view not moderated SAS files"),
                ]
            },
        ),
    ]
