# Generated by Django 4.2.17 on 2025-01-25 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("sas", "0006_move_the_whole_sas")]

    operations = [
        migrations.AlterField(
            model_name="peoplepicturerelation",
            name="picture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="sas.picture",
                verbose_name="picture",
            ),
        ),
        migrations.AlterField(
            model_name="picturemoderationrequest",
            name="picture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_requests",
                to="sas.picture",
                verbose_name="Picture",
            ),
        ),
    ]
