# Generated by Django 4.2.20 on 2025-03-14 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("accounting", "0005_auto_20170324_0917")]

    operations = [
        migrations.RemoveField(model_name="bankaccount", name="club"),
        migrations.RemoveField(model_name="clubaccount", name="bank_account"),
        migrations.RemoveField(model_name="clubaccount", name="club"),
        migrations.DeleteModel(name="Company"),
        migrations.RemoveField(model_name="generaljournal", name="club_account"),
        migrations.AlterUniqueTogether(name="label", unique_together=None),
        migrations.RemoveField(model_name="label", name="club_account"),
        migrations.AlterUniqueTogether(name="operation", unique_together=None),
        migrations.RemoveField(model_name="operation", name="accounting_type"),
        migrations.RemoveField(model_name="operation", name="invoice"),
        migrations.RemoveField(model_name="operation", name="journal"),
        migrations.RemoveField(model_name="operation", name="label"),
        migrations.RemoveField(model_name="operation", name="linked_operation"),
        migrations.RemoveField(model_name="operation", name="simpleaccounting_type"),
        migrations.RemoveField(
            model_name="simplifiedaccountingtype", name="accounting_type"
        ),
        migrations.DeleteModel(name="AccountingType"),
        migrations.DeleteModel(name="BankAccount"),
        migrations.DeleteModel(name="ClubAccount"),
        migrations.DeleteModel(name="GeneralJournal"),
        migrations.DeleteModel(name="Label"),
        migrations.DeleteModel(name="Operation"),
        migrations.DeleteModel(name="SimplifiedAccountingType"),
    ]
