name: deploy_docs
on:
  push:
    branches:
      - master
env:
  SECRET_KEY: notTheRealOne
  DATABASE_URL: sqlite:///db.sqlite3
  CACHE_URL: redis://127.0.0.1:6379/0
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_project
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: uv run mkdocs gh-deploy --force