name: Sith taiste

on:
  push:
    branches: [taiste]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: taiste
    timeout-minutes: 30

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
        # Proxy
        proxy_host : ${{secrets.PROXY_HOST}}
        proxy_port : ${{secrets.PROXY_PORT}}
        proxy_username : ${{secrets.PROXY_USER}}
        proxy_passphrase: ${{secrets.PROXY_PASSPHRASE}}
        proxy_key: ${{secrets.PROXY_KEY}}

        # Serveur web
        host: ${{secrets.HOST}}
        port : ${{secrets.PORT}}
        username : ${{secrets.USER}}
        key: ${{secrets.KEY}}

        script_stop: true

        # See https://github.com/ae-utbm/sith/wiki/GitHub-Actions#deployment-action
        script: |
          export PATH="$HOME/.poetry/bin:$PATH"
          pushd ${{secrets.SITH_PATH}}

          git fetch
          git reset --hard origin/taiste
          poetry install --with prod --without docs,tests
          npm install
          poetry run ./manage.py install_xapian
          poetry run ./manage.py migrate
          poetry run ./manage.py collectstatic --clear --clear-generated --noinput
          poetry run ./manage.py compilemessages

          sudo systemctl restart uwsgi
